# Generated by Django 4.1.3 on 2022-12-19 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('brand_id', models.AutoField(primary_key=True, serialize=False)),
                ('brand_name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('car_id', models.AutoField(primary_key=True, serialize=False)),
                ('car_name', models.CharField(max_length=45)),
                ('price', models.IntegerField()),
                ('color', models.CharField(max_length=10)),
                ('reg_num', models.CharField(max_length=13)),
                ('km_driven', models.IntegerField()),
                ('seats', models.IntegerField()),
                ('fuel_type', models.CharField(max_length=10)),
                ('purc_date', models.DateField()),
                ('no_of_owner', models.IntegerField()),
                ('transmission', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['car_id'],
            },
        ),
        migrations.CreateModel(
            name='CarRequest',
            fields=[
                ('car_request_id', models.AutoField(primary_key=True, serialize=False)),
                ('car_name', models.CharField(max_length=45)),
                ('car_price', models.IntegerField()),
                ('fuel_type', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('pending', 'PENDING'), ('accepted', 'ACCEPTED'), ('cancel', 'CANCEL')], default='PENDING', max_length=10)),
                ('color', models.CharField(max_length=10)),
                ('km_driven', models.IntegerField()),
                ('model_name', models.CharField(max_length=45)),
                ('transmmision', models.CharField(max_length=30)),
                ('image', models.ImageField(max_length=300, upload_to='req_car_img/')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('com_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('address', models.CharField(max_length=45)),
                ('contact', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=45, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('pay_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('car_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.car')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('model_id', models.AutoField(primary_key=True, serialize=False)),
                ('model_name', models.CharField(max_length=45)),
                ('year', models.CharField(default='2022', max_length=4)),
                ('engine', models.CharField(max_length=30)),
                ('car_stock', models.IntegerField(default=1)),
                ('description', models.CharField(max_length=200)),
                ('brand_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.brand')),
            ],
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('inquiry_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=300)),
                ('inq_text', models.TextField(max_length=300)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image_path', models.ImageField(upload_to='images/')),
                ('car_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.car')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('feedback_text', models.TextField(max_length=300)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('comp_id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField(max_length=300)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompanySell',
            fields=[
                ('car_sell_id', models.AutoField(primary_key=True, serialize=False)),
                ('sell_date', models.DateField()),
                ('car_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.car')),
                ('company_id', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.company')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purc_date', models.DateField()),
                ('car_request_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.carrequest')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CarParts',
            fields=[
                ('car_parts_id', models.AutoField(primary_key=True, serialize=False)),
                ('part_name', models.CharField(max_length=45)),
                ('price', models.IntegerField()),
                ('car_request_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.carrequest')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='company_id',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.company'),
        ),
        migrations.AddField(
            model_name='car',
            name='model_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.model'),
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('area_pincode', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('area_name', models.CharField(max_length=45)),
                ('city_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.city')),
            ],
        ),
    ]
