# Generated by Django 4.1.3 on 2022-12-11 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserNew',
        ),
    ]
