# Generated by Django 4.1.3 on 2022-12-11 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_user_usernew'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.DeleteModel(
            name='Nayan',
        ),
        migrations.DeleteModel(
            name='UserNew',
        ),
    ]
