# Generated by Django 4.1.3 on 2022-12-19 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0003_delete_companysell'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companypurchase',
            old_name='car_request_id',
            new_name='req_id',
        ),
        migrations.RenameField(
            model_name='complain',
            old_name='comp_id',
            new_name='company_id',
        ),
        migrations.CreateModel(
            name='CompanySell',
            fields=[
                ('sell_id', models.AutoField(primary_key=True, serialize=False)),
                ('sell_date', models.DateField()),
                ('car_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.car')),
                ('company_id', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.company')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
