# Generated by Django 4.1.3 on 2022-12-11 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0003_delete_admin_delete_car_delete_nayan_delete_usernew'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('area_pincode', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('area_name', models.CharField(max_length=45)),
                ('city_city', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.city')),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('phone', models.IntegerField()),
                ('email', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('area_area_pincode', models.ForeignKey(db_column='area_area_pincode', on_delete=django.db.models.deletion.DO_NOTHING, to='shop.area')),
            ],
        ),
    ]
