# Generated by Django 4.1.3 on 2022-12-19 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_rename_car_request_id_companypurchase_req_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='sold_out',
            field=models.IntegerField(choices=[(0, 0), (1, 1)], default=0),
        ),
    ]
