# Generated by Django 4.1.3 on 2022-12-11 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_brand_brand_id_alter_car_car_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='reg_num',
            field=models.CharField(max_length=13),
        ),
    ]
