# Generated by Django 4.1.3 on 2022-12-20 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_brand_brand_name_alter_model_model_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='complain',
            name='subject',
            field=models.CharField(default='', max_length=50),
        ),
    ]
