# Generated by Django 4.1.3 on 2022-12-11 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_admin_phone_alter_company_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='com_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
