# Generated by Django 4.1.3 on 2022-12-11 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_brand_brand_id_alter_car_car_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companypurchase',
            old_name='user_user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='companysell',
            old_name='company_com_id',
            new_name='com_id',
        ),
        migrations.RenameField(
            model_name='companysell',
            old_name='user_user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='complain',
            old_name='user_user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='car_car',
            new_name='car_id',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='user_user',
            new_name='user_id',
        ),
    ]
