# Generated by Django 4.1.3 on 2022-12-24 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_delete_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrequest',
            old_name='transmmision',
            new_name='transmission',
        ),
        migrations.RemoveField(
            model_name='model',
            name='car_stock',
        ),
        migrations.AlterField(
            model_name='area',
            name='area_pincode',
            field=models.CharField(max_length=6, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='city_name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
