# Generated by Django 4.1.3 on 2022-12-11 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_rename_user_user_companypurchase_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='model',
            old_name='model_no',
            new_name='engine',
        ),
        migrations.AddField(
            model_name='model',
            name='year',
            field=models.CharField(default='2022', max_length=4),
        ),
    ]
