# Generated by Django 4.1.3 on 2022-12-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_rename_model_no_model_engine_model_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='engine',
            field=models.CharField(max_length=30),
        ),
    ]
