# Generated by Django 4.1.3 on 2022-12-24 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shop.helpers


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0013_rename_text_complain_complain_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('review_text', models.TextField(max_length=300, validators=[shop.helpers.clean_review_text])),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='area',
            name='area_name',
            field=models.CharField(max_length=45, validators=[shop.helpers.clean_area_pincode]),
        ),
        migrations.AlterField(
            model_name='brand',
            name='brand_name',
            field=models.CharField(max_length=45, unique=True, validators=[shop.helpers.clean_brand_name]),
        ),
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(max_length=10, validators=[shop.helpers.clean_color]),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(max_length=10, validators=[shop.helpers.clean_fuel_type]),
        ),
        migrations.AlterField(
            model_name='car',
            name='reg_num',
            field=models.CharField(max_length=13, validators=[shop.helpers.clean_regno]),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(max_length=30, validators=[shop.helpers.clean_transmission]),
        ),
        migrations.AlterField(
            model_name='carparts',
            name='part_name',
            field=models.CharField(max_length=45, validators=[shop.helpers.clean_car_parts]),
        ),
        migrations.AlterField(
            model_name='city',
            name='city_name',
            field=models.CharField(max_length=20, unique=True, validators=[shop.helpers.clean_city_name]),
        ),
        migrations.AlterField(
            model_name='company',
            name='contact',
            field=models.CharField(max_length=10, validators=[shop.helpers.clean_contact]),
        ),
        migrations.AlterField(
            model_name='complain',
            name='complain_text',
            field=models.TextField(max_length=300, validators=[shop.helpers.clean_complain_text]),
        ),
        migrations.AlterField(
            model_name='complain',
            name='subject',
            field=models.CharField(max_length=50, validators=[shop.helpers.clean_complain_sub]),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='inq_text',
            field=models.TextField(max_length=300, validators=[shop.helpers.clean_inq_text]),
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
