# Generated by Django 4.1.3 on 2022-12-11 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_model_engine'),
    ]

    operations = [
        migrations.RenameField(
            model_name='model',
            old_name='brand_id',
            new_name='brand_name',
        ),
    ]
