# Generated by Django 4.1.3 on 2022-12-24 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_review_alter_area_area_name_alter_brand_brand_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complain',
            old_name='company_id',
            new_name='complain_id',
        ),
    ]
