# Generated by Django 4.1.3 on 2022-12-11 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_rename_brand_id_model_brand_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='model',
            old_name='brand_name',
            new_name='brand_id',
        ),
    ]
