# Generated by Django 4.1.3 on 2022-12-24 20:03

from django.db import migrations, models
import shop.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_rename_company_id_complain_complain_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='area_name',
            field=models.CharField(max_length=45, validators=[shop.helpers.clean_area_name]),
        ),
        migrations.AlterField(
            model_name='area',
            name='area_pincode',
            field=models.CharField(max_length=6, primary_key=True, serialize=False, unique=True, validators=[shop.helpers.clean_area_pincode]),
        ),
        migrations.AlterField(
            model_name='carrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'PENDING'), ('Accepted', 'ACCEPTED'), ('Cancel', 'CANCEL')], default='Pending', max_length=10),
        ),
    ]
