# Generated by Django 4.1.3 on 2022-12-11 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_rename_brand_name_model_brand_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='engine_type',
        ),
    ]
