# Generated by Django 4.1.3 on 2022-12-11 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_alter_companysell_com_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysell',
            name='com_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.company'),
        ),
    ]
