# Generated by Django 4.1.3 on 2022-12-11 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_alter_companysell_com_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('accepted', 'ACCEPTED'), ('cancel', 'CANCEL')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='complain',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
