# Generated by Django 4.1.3 on 2022-12-11 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_alter_carrequest_status_alter_complain_date_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='text',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback_text',
            field=models.TextField(max_length=300),
        ),
    ]
