# Generated by Django 4.1.3 on 2022-12-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_alter_inquiry_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='text',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='inq_text',
            field=models.TextField(max_length=300),
        ),
    ]
