# Generated by Django 4.1.3 on 2022-12-14 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_alter_complain_text_alter_inquiry_inq_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
