# Generated by Django 4.1.3 on 2022-12-14 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_alter_payment_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=45, unique=True),
        ),
    ]
