# Generated by Django 4.1.3 on 2022-12-14 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_alter_model_brand_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='area',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='admin',
            name='area_pincode',
            field=models.ForeignKey(db_column='area_area_pincode', null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.area'),
        ),
        migrations.AlterField(
            model_name='area',
            name='city_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.city'),
        ),
        migrations.AlterField(
            model_name='car',
            name='company_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.company'),
        ),
        migrations.AlterField(
            model_name='carparts',
            name='car_request_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.carrequest'),
        ),
        migrations.AlterField(
            model_name='carrequest',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.user'),
        ),
        migrations.AlterField(
            model_name='companypurchase',
            name='car_request_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.carrequest'),
        ),
        migrations.AlterField(
            model_name='companypurchase',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.user'),
        ),
        migrations.AlterField(
            model_name='companysell',
            name='car_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.car'),
        ),
        migrations.AlterField(
            model_name='companysell',
            name='com_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.company'),
        ),
        migrations.AlterField(
            model_name='companysell',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.user'),
        ),
        migrations.AlterField(
            model_name='complain',
            name='car_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.car'),
        ),
        migrations.AlterField(
            model_name='complain',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.user'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='car_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.car'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.user'),
        ),
        migrations.AlterField(
            model_name='image',
            name='car_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.car'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.user'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='car_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.car'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='area_pincode',
            field=models.ForeignKey(db_column='area_area_pincode', null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.area'),
        ),
        migrations.AlterField(
            model_name='user',
            name='company_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.company'),
        ),
    ]
