# Generated by Django 4.1.3 on 2022-12-14 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_admin_area_alter_admin_area_pincode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='area_pincode',
        ),
    ]
